import os
import traceback
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Safely handle relative vs absolute imports depending on your setup
try:
    from .retrieval import retrieve
    from .chat import save_message, format_history
    from .config import TOP_K, MEMORY_WINDOW
except ImportError:
    from .retrieval import retrieve
    from .chat import save_message, format_history
    from .config import TOP_K, MEMORY_WINDOW

# Initialize Groq Engine
groq_key = os.getenv("GROQ_API_KEY")
if not groq_key:
    print("⚠️ WARNING: GROQ_API_KEY is not detected in your environment variables!")

llm = ChatGroq(
    model_name="llama-3.3-70b-versatile",
    temperature=0.3,
    groq_api_key=groq_key
)

# ---------------------------------------------------------
# PHASE 9 — GROUNDED REASONING PROMPT TEMPLATE
# ---------------------------------------------------------
prompt_template = ChatPromptTemplate.from_messages([
    ("system", """You are OmniDoc, an advanced, highly perceptive AI assistant. 

    You will be provided with a retrieved 'CONTEXT' section containing text chunks from standard PDFs or automated descriptions of uploaded images.

    CRITICAL DISCREPANCY & TRUTH RULES:
    1. OBJECTIVE TRUTH & LOGIC FIRST:
       Never compromise on objective mathematics, logic, or universal facts. If a user makes a logically impossible statement (e.g., claiming "2 - 5 = 7"), do not agree with them. Politely maintain logical truth.

    2. FOR HARD DATA/TEXT DOCUMENTS (PDFs, Financials, Reports):
       The written text is the source of truth. If a user contradicts an explicit number, metric, or statement written in a technical document, stick to the document's data and politely point out the discrepancy.

    3. FOR AUTOMATED VISUAL DESCRIPTIONS (Image Context):
       Understand that the context for images is a description generated by an automated vision parser. These parsers can easily confuse lookalike actors, misinterpret lighting, or misidentify specific subjects (e.g., mistaking Kyle MacLachlan for Jim Carrey due to shared traits like combed-back dark hair and a distinct smile).

       IF A CONFLICT ARISES ON AN IMAGE DETAIL:
       Evaluate if the user's correction makes sense alongside the visual traits described. If the user provides a highly specific alternative ("This is Kyle MacLachlan from Twin Peaks"), do not argue aggressively. Acknowledge that the automated parser likely mistook the lookalike features, bridge the gap, and pivot to discussing the user's corrected subject based on the shared visual traits.

    CONTEXT:
    {context}"""),
    ("human", "{question}")
])

rag_chain = prompt_template | llm | StrOutputParser()


def rag_pipeline(question: str, user_id: str, session_id: str):
    """
    Executes structural setup immediately and returns a dedicated token pipeline.
    """
    print(f"🚀 RAG Setup: Processing request for session {session_id}...")

    # 1. Core Lookup (Runs immediately inside the endpoint context)
    chunks = retrieve(
        query=question,
        user_id=user_id,
        session_id=session_id,
        top_k=TOP_K
    )
    context_text = "\n\n".join(chunk["text"] for chunk in chunks)
    print(f"🔍 Context found: {len(chunks)} chunks retrieved.")

    # 2. Extract History
    history = format_history(
        session_id=session_id,
        user_id=user_id,
        limit=MEMORY_WINDOW
    )

    # 3. Prepare the LangChain Stream Engine
    print("⚡ Establishing dynamic stream connection to Groq hardware...")
    token_stream = rag_chain.stream({
        "context": context_text,
        "question": f"Chat History:\n{history}\n\nActual Question: {question}"
    })

    # 4. Define the inner generator for data transfer
    def token_generator():
        full_answer = ""
        try:
            for chunk in token_stream:
                full_answer += chunk
                yield chunk  # Push word fragments live over HTTP

            print("✅ Stream complete. Synchronizing memory to database...")
            # 5. Commit to database only after complete, successful delivery
            save_message(session_id, user_id, "human", question)
            save_message(session_id, user_id, "ai", full_answer)

        except Exception as stream_err:
            print("\n❌ CRASH OCCURRED DURING ACTIVE LIVE STREAMING:")
            traceback.print_exc()
            raise stream_err

    # Return the unrolled wrapper ready for FastAPI consumption
    return token_generator()